development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jenkins_rails_app_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jenkins_rails_app
  pool: 5
  username: jenkins_rails_app
  password: jenkins_rails_app
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jenkins_rails_app_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
